import CTAForm from "../../../components/CTAForm";

export default function Page() {
    return (
        <><main className="flex min-h-screen flex-col">
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />

            {/* ========== HERO SECTION ========== */}
            <section className="itinfra-hero flex min-h-[720px] flex-col items-start justify-between gap-[50px] overflow-hidden bg-cover bg-center px-[24px] py-[60px] font-sans lg:flex-row lg:items-center lg:px-[80px] lg:py-20" style={{ backgroundImage: "url('/images/it-solutions/it-infrastructure.png')", backgroundSize: "cover", backgroundPosition: "center", fontFamily: "'Inter', sans-serif" }}>
                <div className="itinfra-left max-w-[620px]">
                    <div className="itinfra-badge mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3.5 py-2 text-[13px] font-medium text-[#C7D7FF] backdrop-blur-[10px]"><i className="fa-solid fa-circle text-[10px] text-[#3B82F6]"></i>Infrastructure Solutions & Services</div>
                    <h1 className="itinfra-title mb-6 text-4xl font-extrabold leading-[1.05] text-white md:text-5xl lg:text-[56px]">Fondasi IT yang <span className="text-[#69A6FF]">Andal</span> untuk Bisnis Masa Depan</h1>
                    <p className="itinfra-desc mb-10 max-w-[560px] text-[17px] leading-[1.8] text-white/75">PT. United Teknologi Integrasi menghadirkan solusi Infrastructure terintegrasi — dari server, storage, cloud, hingga data center — yang dirancang untuk efisiensi, keamanan, dan skalabilitas penuh.</p>
                    <div className="itinfra-buttons mb-[60px] flex gap-3.5"><a href="#" className="btn-primary flex items-center gap-2.5 rounded-xl bg-white px-6 py-[15px] text-[15px] font-semibold text-[#0A2A83] no-underline"><i className="fa-solid fa-phone"></i>Konsultasi Gratis</a><a href="#" className="btn-secondary flex items-center gap-2.5 rounded-xl border border-white/20 px-6 py-[15px] text-[15px] font-medium text-white no-underline">Lihat Solusi <i className="fa-solid fa-arrow-right"></i></a></div>
                    <div className="itinfra-stats flex flex-wrap gap-[30px] md:gap-[50px]"><div className="stat"><h2 className="text-[38px] font-extrabold text-white">20+</h2><p className="mt-2 text-sm text-white/65">Tahun Pengalaman</p></div><div className="stat"><h2 className="text-[38px] font-extrabold text-white">500+</h2><p className="mt-2 text-sm text-white/65">Klien Enterprise</p></div><div className="stat"><h2 className="text-[38px] font-extrabold text-white">24/7</h2><p className="mt-2 text-sm text-white/65">Support Coverage</p></div></div>
                </div>
                <div className="itinfra-right w-full max-w-[500px] lg:w-[470px]"><div className="stack-card rounded-3xl border border-white/10 bg-white/10 p-7 backdrop-blur-[12px]"><div className="stack-title mb-[18px] text-xs font-semibold tracking-[2px] text-white/55">INFRASTRUCTURE STACK</div><div className="stack-grid grid grid-cols-1 gap-3.5 sm:grid-cols-2"><div className="stack-item rounded-xl border border-white/10 bg-white/10 p-4"><div className="stack-icon mb-3 flex h-9 w-9 items-center justify-center rounded-[10px] bg-white/10 text-[#8AB5FF]"><i className="fa-solid fa-server"></i></div><h4 className="mb-1 text-sm font-semibold text-white">Server</h4><p className="text-xs text-white/50">Rack & Blade</p></div><div className="stack-item rounded-xl border border-white/10 bg-white/10 p-4"><div className="stack-icon mb-3 flex h-9 w-9 items-center justify-center rounded-[10px] bg-white/10 text-[#8AB5FF]"><i className="fa-solid fa-database"></i></div><h4 className="mb-1 text-sm font-semibold text-white">Storage</h4><p className="text-xs text-white/50">SAN & NAS</p></div><div className="stack-item rounded-xl border border-white/10 bg-white/10 p-4"><div className="stack-icon mb-3 flex h-9 w-9 items-center justify-center rounded-[10px] bg-white/10 text-[#8AB5FF]"><i className="fa-solid fa-cloud"></i></div><h4 className="mb-1 text-sm font-semibold text-white">Cloud</h4><p className="text-xs text-white/50">Hybrid & Multi</p></div><div className="stack-item rounded-xl border border-white/10 bg-white/10 p-4"><div className="stack-icon mb-3 flex h-9 w-9 items-center justify-center rounded-[10px] bg-white/10 text-[#8AB5FF]"><i className="fa-solid fa-microchip"></i></div><h4 className="mb-1 text-sm font-semibold text-white">HCI</h4><p className="text-xs text-white/50">Hyperconverged</p></div><div className="stack-item rounded-xl border border-white/10 bg-white/10 p-4"><div className="stack-icon mb-3 flex h-9 w-9 items-center justify-center rounded-[10px] bg-white/10 text-[#8AB5FF]"><i className="fa-solid fa-shield-halved"></i></div><h4 className="mb-1 text-sm font-semibold text-white">Backup</h4><p className="text-xs text-white/50">DR & BCP</p></div><div className="stack-item rounded-xl border border-white/10 bg-white/10 p-4"><div className="stack-icon mb-3 flex h-9 w-9 items-center justify-center rounded-[10px] bg-white/10 text-[#8AB5FF]"><i className="fa-solid fa-building"></i></div><h4 className="mb-1 text-sm font-semibold text-white">Data Center</h4><p className="text-xs text-white/50">Tier III/IV</p></div></div></div></div>
            </section>

            {/* ========== WHY SECTION ========== */}
            <section className="why-section bg-white px-[24px] py-[60px] md:px-[80px] md:py-[90px]"><div className="why-wrapper flex flex-col gap-[60px] lg:flex-row"><div className="why-left flex-1"><div className="performance-card rounded-[22px] bg-[#EAF2FF] p-5"><div className="performance-top mb-3.5 rounded-[14px] bg-white p-5"><div className="performance-title mb-[15px] flex items-start gap-2.5"><i className="fa-solid fa-wave-square mt-0.5 text-[#3B82F6]"></i><div className="performance-text"><h4 className="m-0 text-sm font-bold leading-tight text-[#173B85]">System Performance</h4><h5 className="mt-1 text-[11px] font-medium leading-tight text-[#9CA3AF]">Real-time Monitoring</h5></div></div><div className="metric mb-3"><div className="metric-head mb-1.5 flex justify-between text-xs text-[#6B7280]"><span>Uptime</span><span>99.9%</span></div><div className="metric-bar h-1.5 overflow-hidden rounded-full bg-[#dbe7ff]"><div className="metric-fill h-full bg-[#3B82F6]" style={{ width: "99%" }}></div></div></div><div className="metric mb-3"><div className="metric-head mb-1.5 flex justify-between text-xs text-[#6B7280]"><span>Speed</span><span>94%</span></div><div className="metric-bar h-1.5 overflow-hidden rounded-full bg-[#dbe7ff]"><div className="metric-fill h-full bg-[#3B82F6]" style={{ width: "94%" }}></div></div></div><div className="metric mb-3"><div className="metric-head mb-1.5 flex justify-between text-xs text-[#6B7280]"><span>Security</span><span>97%</span></div><div className="metric-bar h-1.5 overflow-hidden rounded-full bg-[#dbe7ff]"><div className="metric-fill h-full bg-[#3B82F6]" style={{ width: "98%" }}></div></div></div></div><div className="performance-stats grid grid-cols-2 gap-3"><div className="p-box rounded-[14px] bg-white p-[18px]"><h3 className="mb-1.5 text-[30px] text-[#173B85]">20+</h3><p className="text-[13px] text-[#8A8FA0]">Tahun Pengalaman</p></div><div className="p-box rounded-[14px] bg-white p-[18px]"><h3 className="mb-1.5 text-[30px] text-[#173B85]">500+</h3><p className="text-[13px] text-[#8A8FA0]">Klien Aktif</p></div><div className="p-box rounded-[14px] bg-white p-[18px]"><h3 className="mb-1.5 text-[30px] text-[#173B85]">3</h3><p className="text-[13px] text-[#8A8FA0]">Kantor Lokasi</p></div><div className="p-box rounded-[14px] bg-white p-[18px]"><h3 className="mb-1.5 text-[30px] text-[#173B85]">24/7</h3><p className="text-[13px] text-[#8A8FA0]">NOC Support</p></div></div></div></div>
                <div className="why-right flex-1"><div className="section-label mb-4 flex items-center gap-2.5 text-xs font-bold uppercase text-[#3B82F6] before:h-0.5 before:w-5 before:bg-[#3B82F6] before:content-['']">Mengapa UTI</div><h2 className="why-title mb-[18px] text-3xl font-extrabold leading-[1.2] text-[#112B70] md:text-4xl lg:text-[42px]">IT Infrastructure Bukan Sekadar Hardware</h2><p className="why-desc mb-[30px] leading-[1.8] text-[#6B7280]">UTI memahami bahwa infrastruktur IT yang baik adalah pondasi dari seluruh operasional bisnis. Kami tidak hanya menjual perangkat, kami membangun ekosistem teknologi yang tumbuh bersama bisnis Anda.</p><div className="feature-list flex flex-col gap-3.5"><div className="feature-item flex gap-[18px] rounded-[14px] border border-[#EDF1F7] bg-[#F7F9FC] p-5"><div className="feature-icon flex h-[42px] w-[42px] items-center justify-center rounded-xl bg-[#EAF2FF] text-[#3B82F6]"><i className="fa-solid fa-clock"></i></div><div><h4 className="mb-1.5 text-[15px] text-[#112B70]">Konsultasi & Assessment Mendalam</h4><p className="text-[13px] leading-[1.6] text-[#6B7280]">Tim arsitek IT kami menganalisis kebutuhan spesifik bisnis Anda sebelum merekomendasikan solusi apapun.</p></div></div><div className="feature-item flex gap-[18px] rounded-[14px] border border-[#EDF1F7] bg-[#F7F9FC] p-5"><div className="feature-icon flex h-[42px] w-[42px] items-center justify-center rounded-xl bg-[#EAF2FF] text-[#3B82F6]"><i className="fa-solid fa-shield-halved"></i></div><div><h4 className="mb-1.5 text-[15px] text-[#112B70]">Vendor-Neutral & Multi-Brand</h4><p className="text-[13px] leading-[1.6] text-[#6B7280]">Kami bekerja dengan ratusan brand terkemuka — HPE, Dell, Cisco, Nutanix, VMware — untuk memberikan yang terbaik sesuai anggaran Anda.</p></div></div><div className="feature-item flex gap-[18px] rounded-[14px] border border-[#EDF1F7] bg-[#F7F9FC] p-5"><div className="feature-icon flex h-[42px] w-[42px] items-center justify-center rounded-xl bg-[#EAF2FF] text-[#3B82F6]"><i className="fa-solid fa-headset"></i></div><div><h4 className="mb-1.5 text-[15px] text-[#112B70]">After-Sales Support 24/7</h4><p className="text-[13px] leading-[1.6] text-[#6B7280]">Tim NOC kami siap memantau dan merespons setiap insiden kapanpun — Silver, Gold, hingga Platinum tier.</p></div></div></div></div></div></section>

            {/* ========== SERVICES SECTION ========== */}
            <section className="services-section bg-[#F5F5FD] px-[24px] py-[60px] md:px-[80px] md:py-[100px]">
                <div className="section-label mb-4 flex items-center gap-2.5 text-xs font-bold uppercase text-[#3B82F6] before:h-0.5 before:w-5 before:bg-[#3B82F6] before:content-['']">Layanan Kami</div>
                <h2 className="services-title mb-3.5 text-3xl font-extrabold text-[#112B70] md:text-4xl lg:text-[46px]">Solusi Lengkap dari Hulu ke Hilir</h2><p className="services-desc mb-[50px] max-w-[700px] leading-[1.8] text-[#6B7280]">Dari perencanaan arsitektur hingga implementasi dan maintenance — UTI hadir di setiap tahap perjalanan digital Anda.</p>
                <div className="services-grid grid grid-cols-1 gap-[18px] md:grid-cols-2 lg:grid-cols-3">
                    {[{ num: "01", icon: "server", title: "Server & Compute", desc: "Solusi server enterprise dari rack server, blade server, hingga tower server dengan performa tinggi dan keandalan maksimal untuk beban kerja kritis.", tags: ["HPE ProLiant", "Dell PowerEdge", "Lenovo ThinkSystem"] },
                    { num: "02", icon: "database", title: "Storage Solutions", desc: "All-flash, hybrid storage, SAN, NAS dan object storage untuk kebutuhan data yang terus berkembang dengan performa I/O tinggi.", tags: ["Pure Storage", "NetApp", "EMC Dell"] },
                    { num: "03", icon: "microchip", title: "Hyperconverged (HCI)", desc: "Infrastruktur konvergen yang menyatukan compute, storage dan networking dalam satu platform untuk kemudahan manajemen dan skalabilitas tinggi.", tags: ["Nutanix", "VMware vSAN", "HPE SimpliVity"] },
                    { num: "04", icon: "cloud", title: "Cloud Services", desc: "Migrasi, desain dan manajemen cloud — public, private maupun hybrid cloud dengan optimasi biaya dan keamanan data terjamin.", tags: ["AWS", "Azure", "Google Cloud"] },
                    { num: "05", icon: "shield-halved", title: "Backup & Disaster Recovery", desc: "Solusi backup komprehensif dan disaster recovery plan yang memastikan data bisnis Anda selalu aman dan operasional tetap berjalan.", tags: ["Veeam", "Commvault", "Veritas"] },
                    { num: "06", icon: "building", title: "Data Center", desc: "Desain, pembangunan dan pengelolaan data center dari Tier I hingga Tier IV termasuk power, cooling, cabling dan sistem monitoring.", tags: ["Schneider Electric", "APC", "Emerson"] }
                    ].map((s, i) => <div key={i} className="service-card flex min-h-[250px] flex-col rounded-[14px] border border-[#E8EDF8] bg-white p-[18px]"><div className="service-number mb-3.5 text-[11px] font-bold text-[#9DB4F5]">{s.num}</div><div className="service-icon mb-3.5 flex h-7 w-7 items-center justify-center rounded-lg bg-[#EEF4FF] text-xs text-[#2F6CF6]"><i className={`fa-solid fa-${s.icon}`}></i></div><h3 className="mb-2.5 text-[15px] font-bold leading-tight text-[#112B70]">{s.title}</h3><p className="mb-auto text-xs leading-[1.8] text-[#7D8596]">{s.desc}</p><div className="tags mt-[18px] flex flex-wrap gap-1.5">{s.tags.map((t, j) => <span key={j} className="rounded-full bg-[#EEF4FF] px-2.5 py-1 text-[10px] font-medium text-[#3D6CE6]">{t}</span>)}</div></div>)}
                </div>
            </section>

            {/* ========== SOLUTION DETAIL SECTION ========== */}
            <section className="solution-detail bg-white px-[24px] py-[60px] md:px-[80px] md:py-[100px]"><div className="solution-wrapper flex flex-col gap-[80px] lg:flex-row lg:items-center"><div className="solution-left max-w-[600px] flex-1"><div className="section-label mb-4 flex items-center gap-2.5 text-xs font-bold uppercase text-[#3B82F6] before:h-0.5 before:w-5 before:bg-[#3B82F6] before:content-['']">Detail Solusi</div><h2 className="solution-title mb-[18px] text-3xl font-extrabold leading-[1.15] text-[#102C73] md:text-4xl lg:text-[48px]">Arsitektur yang Tepat untuk Setiap Kebutuhan</h2><p className="solution-desc mb-6 leading-[1.8] text-[#6B7280]">Setiap bisnis memiliki kebutuhan yang unik. UTI menyediakan solusi yang dapat dikustomisasi sepenuhnya.</p><div className="solution-badge mb-6 inline-block rounded-full bg-[#EEF4FF] px-3.5 py-2 text-[13px] font-semibold text-[#3B82F6]">Solusi Terpopuler</div><h3 className="solution-subtitle mb-3.5 text-2xl font-extrabold text-[#102C73] md:text-3xl lg:text-[34px]">Manajemen Server & Storage Enterprise</h3><p className="solution-desc mb-6 leading-[1.8] text-[#6B7280]">Membangun fondasi IT yang kuat dimulai dari server dan storage yang tepat. UTI menyediakan solusi end-to-end mulai dari sizing, procurement, implementasi hingga monitoring berkelanjutan.</p><ul className="solution-list mb-6 list-none p-0">{[{ text: "Monitoring server 24/7 dengan alerting real-time" }, { text: "Load balancing & pemeliharaan preventif terjadwal" }, { text: "Enkripsi data & kontrol akses berbasis peran (RBAC)" }, { text: "Scalable storage mulai dari TB hingga Petabyte" }, { text: "Garansi SLA respons 4 jam untuk hardware kritis" }].map((item, i) => <li key={i} className="mb-3.5 flex items-start gap-2.5 leading-[1.7] text-[#4B5563]"><i className="fa-solid fa-circle-check mt-1 text-[#22C55E]"></i>{item.text}</li>)}</ul><a href="#" className="solution-btn inline-flex items-center gap-2.5 rounded-[10px] bg-[#102C73] px-[22px] py-3.5 font-semibold text-white no-underline">Konsultasi Sekarang <i className="fa-solid fa-arrow-right"></i></a></div>
                <div className="solution-right flex-1"><div className="arch-card rounded-[22px] bg-[#EAF2FF] p-[18px]"><div className="arch-grid grid grid-cols-1 gap-3.5 sm:grid-cols-2"><div className="arch-item rounded-[14px] bg-white p-6"><div className="arch-icon mb-4 flex h-[38px] w-[38px] items-center justify-center rounded-[10px] bg-[#EEF4FF] text-[#3B82F6]"><i className="fa-solid fa-wave-square"></i></div><h3 className="mb-1.5 text-[30px] font-extrabold text-[#102C73]">99.9%</h3><p className="text-[13px] text-[#7B8192]">Uptime SLA Guarantee</p></div><div className="arch-item rounded-[14px] bg-white p-6"><div className="arch-icon mb-4 flex h-[38px] w-[38px] items-center justify-center rounded-[10px] bg-[#EEF4FF] text-[#3B82F6]"><i className="fa-regular fa-clock"></i></div><h3 className="mb-1.5 text-[30px] font-extrabold text-[#102C73]">&lt; 4 Jam</h3><p className="text-[13px] text-[#7B8192]">Response Time Hardware</p></div><div className="arch-item rounded-[14px] bg-white p-6"><div className="arch-icon mb-4 flex h-[38px] w-[38px] items-center justify-center rounded-[10px] bg-[#EEF4FF] text-[#3B82F6]"><i className="fa-solid fa-shield-halved"></i></div><h3 className="mb-1.5 text-[30px] font-extrabold text-[#102C73]">256-bit</h3><p className="text-[13px] text-[#7B8192]">Data Encryption AES</p></div><div className="arch-item rounded-[14px] bg-white p-6"><div className="arch-icon mb-4 flex h-[38px] w-[38px] items-center justify-center rounded-[10px] bg-[#EEF4FF] text-[#3B82F6]"><i className="fa-solid fa-circle-nodes"></i></div><h3 className="mb-1.5 text-[30px] font-extrabold text-[#102C73]">∞ Scale</h3><p className="text-[13px] text-[#7B8192]">Horizontal Scalability</p></div></div></div></div></div></section>

            {/* ========== PROCESS SECTION ========== */}
            <section className="process-section bg-[#0E2A78] px-[24px] py-[60px] text-center md:px-[80px] md:py-[110px]"><div className="section-label process-label mb-4 flex items-center justify-center gap-2.5 text-xs font-bold uppercase text-[#7FB1FF] before:h-0.5 before:w-5 before:bg-[#7FB1FF] before:content-['']">Cara Kerja Kami</div><h2 className="process-title my-5 text-3xl font-extrabold text-white md:text-4xl lg:text-[48px]">Proses Terstruktur, Hasil Terukur</h2><p className="process-desc mx-auto max-w-[700px] leading-[1.8] text-white/70">Metodologi implementasi kami telah terbukti di ratusan proyek enterprise di seluruh Indonesia.</p>
                <div className="process-line relative mt-[90px] flex flex-wrap justify-between before:absolute before:left-0 before:top-[18px] before:h-px before:w-full before:bg-white/15 max-md:before:hidden"><div className="process-step relative z-[2] w-full md:w-[23%]"><div className="process-number mx-auto mb-[30px] flex h-[42px] w-[42px] items-center justify-center rounded-full bg-white/20 font-bold text-[#9BC0FF]">01</div><h4 className="mb-3 text-base text-white">Assessment & Konsultasi</h4><p className="text-[13px] leading-[1.7] text-white/65">Analisis mendalam terhadap kebutuhan bisnis, infrastruktur eksisting, dan target transformasi digital Anda.</p></div><div className="process-step relative z-[2] w-full md:w-[23%]"><div className="process-number mx-auto mb-[30px] flex h-[42px] w-[42px] items-center justify-center rounded-full bg-white/20 font-bold text-[#9BC0FF]">02</div><h4 className="mb-3 text-base text-white">Desain Arsitektur</h4><p className="text-[13px] leading-[1.7] text-white/65">Tim arsitek kami merancang solusi yang optimal — baik dari sisi performa, keamanan, maupun total cost of ownership.</p></div><div className="process-step relative z-[2] w-full md:w-[23%]"><div className="process-number mx-auto mb-[30px] flex h-[42px] w-[42px] items-center justify-center rounded-full bg-white/20 font-bold text-[#9BC0FF]">03</div><h4 className="mb-3 text-base text-white">Implementasi & Migrasi</h4><p className="text-[13px] leading-[1.7] text-white/65">Deployment terstruktur dengan minimasi downtime, dokumentasi lengkap, dan testing menyeluruh sebelum go-live.</p></div><div className="process-step relative z-[2] w-full md:w-[23%]"><div className="process-number mx-auto mb-[30px] flex h-[42px] w-[42px] items-center justify-center rounded-full bg-white/20 font-bold text-[#9BC0FF]">04</div><h4 className="mb-3 text-base text-white">Monitoring & Support</h4><p className="text-[13px] leading-[1.7] text-white/65">NOC 24/7, pemeliharaan preventif, dan dedicated support engineer untuk memastikan sistem selalu optimal.</p></div></div>
            </section>


        </main>
        <CTAForm backgroundColor="#0E2A78" brandColor="#0E2A78" />
        </>
    );
}