import CTAForm from "../../../components/CTAForm";

export default function Page() {
    return (
        <><main className="flex min-h-screen flex-col">
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />

            {/* HERO SECTION */}
            <section className="relative flex min-h-screen flex-col items-center justify-between gap-[50px] overflow-hidden bg-cover bg-center px-[24px] py-20 font-sans lg:flex-row lg:gap-0 lg:px-[80px]" style={{ backgroundImage: "url('/images/it-solutions/unified-communication.png')", backgroundSize: "cover", backgroundPosition: "center", fontFamily: "'Inter', sans-serif" }}>
                <div className="max-w-[540px]">
                    <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/12 px-[14px] py-2 text-xs font-medium text-[#D8B4FE]">Unified Communication & Collaboration</div>
                    <h1 className="mb-6 text-4xl font-extrabold leading-[1.05] text-white md:text-5xl lg:text-[60px]">Satu Platform, <span className="text-[#C4B5FD]">Semua Cara</span> Berkomunikasi</h1>
                    <p className="mb-9 text-[17px] leading-[1.9] text-white/75">PT. United Teknologi Integrasi menghadirkan solusi UCC terintegrasi — voice, video, messaging, whiteboard, dan kolaborasi real-time — yang menghubungkan tim Anda dari mana saja, di perangkat apa pun.</p>
                    <div className="mb-[55px] flex gap-[14px]"><a href="#" className="flex items-center gap-[10px] rounded-xl bg-white px-[22px] py-[14px] text-sm font-bold text-[#1E1B4B] no-underline"><i className="fa-solid fa-video"></i> Coba Demo Gratis</a><a href="#" className="flex items-center gap-[10px] rounded-xl border border-white/15 px-[22px] py-[14px] text-sm font-semibold text-white no-underline">Lihat Solusi <i className="fa-solid fa-arrow-right"></i></a></div>
                    <div className="flex flex-wrap gap-6 border-t border-white/10 pt-6 md:gap-10"><div><h3 className="text-3xl font-extrabold text-white md:text-[32px]">40%</h3><p className="mt-1.5 text-xs text-white/55">Efisiensi Meeting Lebih Tinggi</p></div><div><h3 className="text-3xl font-extrabold text-white md:text-[32px]">1 Platform</h3><p className="mt-1.5 text-xs text-white/55">Semua Channel Komunikasi</p></div><div><h3 className="text-3xl font-extrabold text-white md:text-[32px]">99.99%</h3><p className="mt-1.5 text-xs text-white/55">Uptime SLA</p></div></div>
                </div>
                <div className="w-full max-w-[650px] lg:w-[560px]">
                    <div className="rounded-[22px] border border-white/10 bg-white/10 p-[22px] backdrop-blur-[14px]">
                        <div className="mb-[18px] flex items-center justify-between"><div className="text-[11px] font-bold tracking-[1.5px] text-white/55">COMMUNICATION HUB</div><div className="text-[11px] font-bold text-[#D8B4FE]">● LIVE</div></div>
                        <div className="mb-[14px] rounded-[14px] border border-white/10 bg-white/10 p-4"><h4 className="mb-[10px] text-sm text-white">All-Hands Q2 2026</h4><div className="mb-3 flex gap-1.5"><div className="flex h-[26px] w-[26px] items-center justify-center rounded-full bg-[#8B5CF6] text-[10px] font-bold text-white">AR</div><div className="flex h-[26px] w-[26px] items-center justify-center rounded-full bg-[#06B6D4] text-[10px] font-bold text-white">SD</div><div className="flex h-[26px] w-[26px] items-center justify-center rounded-full bg-[#22C55E] text-[10px] font-bold text-white">CK</div><div className="flex h-[26px] w-[26px] items-center justify-center rounded-full bg-[#F59E0B] text-[10px] font-bold text-white">DM</div><div className="flex h-[26px] w-[26px] items-center justify-center rounded-full bg-[#8B5CF6] text-[10px] font-bold text-white">+18</div></div><p className="text-[11px] text-white/55">22 peserta · 32 menit berlangsung · Recording aktif</p><div className="mt-2 h-1 rounded-full bg-white/10"><span className="block h-full w-[65%] rounded-full bg-[#C4B5FD]"></span></div></div>
                        <div className="flex flex-col gap-2.5"><div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/10 p-3 px-[14px]"><div className="flex items-center gap-2.5 text-[13px] text-white"><i className="fa-solid fa-phone text-[#C4B5FD]"></i>IP Telephony</div><div className="text-[11px] text-white/45">247 ext aktif</div></div><div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/10 p-3 px-[14px]"><div className="flex items-center gap-2.5 text-[13px] text-white"><i className="fa-solid fa-video text-[#C4B5FD]"></i>Video Conference</div><div className="flex items-center gap-2 text-[11px] text-white/45">12 room aktif<span className="rounded-full bg-[#8B5CF6] px-2 py-0.5 text-[10px] font-bold text-white">NEW</span></div></div><div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/10 p-3 px-[14px]"><div className="flex items-center gap-2.5 text-[13px] text-white"><i className="fa-solid fa-message text-[#C4B5FD]"></i>Team Messaging</div><div className="text-[11px] text-white/45">1,284 pesan hari ini</div></div></div>
                        <div className="mt-[14px] grid grid-cols-1 gap-2.5 sm:grid-cols-3"><div className="rounded-xl border border-white/10 bg-white/10 p-3.5 text-center"><h4 className="text-2xl font-extrabold text-white">22</h4><p className="mt-1 text-[11px] text-white/45">Meeting Aktif</p></div><div className="rounded-xl border border-white/10 bg-white/10 p-3.5 text-center"><h4 className="text-2xl font-extrabold text-white">98%</h4><p className="mt-1 text-[11px] text-white/45">Call Quality</p></div><div className="rounded-xl border border-white/10 bg-white/10 p-3.5 text-center"><h4 className="text-2xl font-extrabold text-white">247</h4><p className="mt-1 text-[11px] text-white/45">Users Online</p></div></div>
                    </div>
                </div>
            </section>

            {/* WHY UCC SECTION */}
            <section className="bg-[#F8FAFC] px-[24px] py-20 font-sans md:px-[80px] md:py-[110px]">
                <div className="mx-auto grid max-w-[1300px] grid-cols-1 gap-[70px] md:grid-cols-2">
                    <div>
                        <div className="rounded-2xl border border-[#FFD0D0] bg-[#F7FAFF] p-[22px]"><div className="mb-2 text-[11px] font-extrabold tracking-[1.5px] text-[#DC2626]">✕ TANPA UNIFIED COMMUNICATION</div><ul className="mt-[14px] list-none"><li className="relative mb-3 pl-6 text-sm leading-[1.7] text-[#475569] before:absolute before:left-0 before:top-0 before:text-[#EF4444] before:content-['✕']">Aplikasi terpisah: email, chat, telepon, Zoom, Slack...</li><li className="relative mb-3 pl-6 text-sm leading-[1.7] text-[#475569] before:absolute before:left-0 before:top-0 before:text-[#EF4444] before:content-['✕']">Konteks percakapan hilang antar platform</li><li className="relative mb-3 pl-6 text-sm leading-[1.7] text-[#475569] before:absolute before:left-0 before:top-0 before:text-[#EF4444] before:content-['✕']">Biaya lisensi berganda, sulit dikelola IT</li><li className="relative mb-3 pl-6 text-sm leading-[1.7] text-[#475569] before:absolute before:left-0 before:top-0 before:text-[#EF4444] before:content-['✕']">Remote team sulit berkolaborasi secara real-time</li></ul></div>
                        <div className="mx-auto my-3.5 h-7 w-px bg-[#DCE3EE]"></div>
                        <div className="rounded-2xl border border-[#B8F0D2] bg-[#F7FAFF] p-[22px]"><div className="mb-2 text-[11px] font-extrabold tracking-[1.5px] text-[#059669]">✓ DENGAN SOLUSI UTI UCC</div><ul className="mt-[14px] list-none"><li className="relative mb-3 pl-6 text-sm leading-[1.7] text-[#475569] before:absolute before:left-0 before:top-0 before:text-[#10B981] before:content-['✓']">Satu platform: voice, video, chat, whiteboard terintegrasi</li><li className="relative mb-3 pl-6 text-sm leading-[1.7] text-[#475569] before:absolute before:left-0 before:top-0 before:text-[#10B981] before:content-['✓']">Riwayat percakapan lengkap lintas channel</li><li className="relative mb-3 pl-6 text-sm leading-[1.7] text-[#475569] before:absolute before:left-0 before:top-0 before:text-[#10B981] before:content-['✓']">Satu lisensi, satu dashboard manajemen terpusat</li><li className="relative mb-3 pl-6 text-sm leading-[1.7] text-[#475569] before:absolute before:left-0 before:top-0 before:text-[#10B981] before:content-['✓']">Kolaborasi real-time dari mana saja, device apa pun</li></ul></div>
                        <div className="mt-[18px] grid grid-cols-1 gap-3 md:grid-cols-3"><div className="rounded-[14px] bg-[#F2F4FF] p-[18px] text-center"><h3 className="text-3xl font-extrabold text-[#112868]">40%</h3><p className="mt-1.5 text-xs text-[#94A3B8]">Efisiensi meeting meningkat</p></div><div className="rounded-[14px] bg-[#F2F4FF] p-[18px] text-center"><h3 className="text-3xl font-extrabold text-[#112868]">30%</h3><p className="mt-1.5 text-xs text-[#94A3B8]">Penghematan biaya komunikasi</p></div><div className="rounded-[14px] bg-[#F2F4FF] p-[18px] text-center"><h3 className="text-3xl font-extrabold text-[#112868]">2×</h3><p className="mt-1.5 text-xs text-[#94A3B8]">Kecepatan keputusan tim</p></div></div>
                    </div>
                    <div><div className="mb-[18px] flex items-center gap-2.5 text-[11px] font-bold tracking-[2px] text-[#2563EB]"><span className="h-0.5 w-[18px] bg-[#2563EB]"></span>MENGAPA UCC</div><h2 className="mb-5 text-3xl font-extrabold leading-[1.08] text-[#112868] md:text-4xl lg:text-[52px]">Komunikasi Terpisah Membunuh Produktivitas</h2><p className="mb-[30px] leading-[1.9] text-[#667085]">Tim modern membutuhkan lebih dari sekadar email. UCC menyatukan semua metode komunikasi dalam satu ekosistem yang saling terhubung untuk menghilangkan friction dan mempercepat kolaborasi.</p>
                        <div className="mb-3.5 flex gap-4 rounded-2xl border border-[#E7ECF5] bg-white p-[18px]"><div className="flex h-[42px] w-[42px] min-w-[42px] items-center justify-center rounded-xl bg-[#F2EDFF] text-[#8B5CF6]"><i className="fa-solid fa-desktop"></i></div><div><h4 className="mb-1.5 text-base text-[#112868]">Hybrid Work Ready</h4><p className="text-[13px] leading-[1.7] text-[#667085]">Solusi kami dirancang untuk era hybrid — karyawan di kantor, di rumah, atau di lapangan bisa berkolaborasi tanpa hambatan teknis.</p></div></div>
                        <div className="mb-3.5 flex gap-4 rounded-2xl border border-[#E7ECF5] bg-white p-[18px]"><div className="flex h-[42px] w-[42px] min-w-[42px] items-center justify-center rounded-xl bg-[#F2EDFF] text-[#8B5CF6]"><i className="fa-solid fa-shield-halved"></i></div><div><h4 className="mb-1.5 text-base text-[#112868]">Enterprise-grade Security</h4><p className="text-[13px] leading-[1.7] text-[#667085]">Enkripsi end-to-end pada seluruh channel komunikasi — voice, video, chat — dengan kontrol akses berbasis peran dan audit log lengkap.</p></div></div>
                        <div className="mb-3.5 flex gap-4 rounded-2xl border border-[#E7ECF5] bg-white p-[18px]"><div className="flex h-[42px] w-[42px] min-w-[42px] items-center justify-center rounded-xl bg-[#F2EDFF] text-[#8B5CF6]"><i className="fa-solid fa-arrow-up-right-dots"></i></div><div><h4 className="mb-1.5 text-base text-[#112868]">Integrasi dengan Sistem Eksisting</h4><p className="text-[13px] leading-[1.7] text-[#667085]">Terhubung mulus dengan Microsoft 365, Google Workspace, CRM, ERP, dan ratusan aplikasi bisnis melalui API dan pre-built connector.</p></div></div>
                    </div>
                </div>
            </section>

            {/* SOLUTIONS SECTION */}
            <section className="bg-[#F7F9FC] px-[24px] py-20 font-sans md:px-[80px] md:py-[110px]">
                <div className="mx-auto max-w-[1300px]"><div className="mb-[18px] flex items-center gap-2.5 text-[11px] font-bold tracking-[2px] text-[#4F7BFF]"><span className="h-0.5 w-[18px] bg-[#4F7BFF]"></span>SOLUSI KAMI</div><h2 className="mb-[18px] text-3xl font-extrabold leading-[1.1] text-[#112868] md:text-4xl lg:text-[54px]">Platform Komunikasi Lengkap dalam <br />Satu Ekosistem</h2><p className="mb-[50px] max-w-[650px] text-base leading-[1.9] text-[#667085]">Dari IP telephony hingga virtual whiteboard — UTI menghadirkan semua yang dibutuhkan tim Anda untuk berkomunikasi dan berkolaborasi secara efektif.</p>
                    <div className="grid grid-cols-1 gap-[18px] md:grid-cols-2 lg:grid-cols-3">
                        {[{num:"01",icon:"phone",title:"IP Telephony & VoIP",desc:"Ganti PABX konvensional dengan sistem IP telephony modern yang lebih fleksibel, scalable, dan hemat biaya.",tags:["Cisco Webex Calling","Avaya","3CX PBX"],color:""},{num:"02",icon:"video",title:"Video Conferencing",desc:"Ruang meeting virtual HD dengan fitur kolaborasi real-time — screen sharing, breakout rooms, recording.",tags:["Cisco Webex","Microsoft Teams","Zoom Rooms"],color:"video"},{num:"03",icon:"message",title:"Team Messaging & Chat",desc:"Platform pesan tim yang terorganisir per channel, project, dan departemen.",tags:["Microsoft Teams","Cisco Webex","Slack Enterprise"],color:"chat"},{num:"04",icon:"chalkboard",title:"Virtual Whiteboard",desc:"Canvas digital tak terbatas untuk brainstorming, mind mapping, dan design thinking bersama tim.",tags:["Cisco Web Board","Microsoft Whiteboard","Miro"],color:"whiteboard"},{num:"05",icon:"mobile-screen-button",title:"Mobilitas & Aksesibilitas",desc:"Akses penuh ke seluruh fitur UCC dari smartphone, tablet, laptop, maupun desktop.",tags:["Mobile App","SSO / MFA","Cross-platform"],color:"mobility"},{num:"06",icon:"headset",title:"Contact Center",desc:"Solusi contact center omnichannel yang menyatukan voice, email, chat, dan social media.",tags:["Cisco UCCX","Avaya CC","Genesys"],color:"contact"}].map((s,i)=><div key={i} className={`rounded-[18px] border border-[#E7ECF5] bg-white p-6 transition-all hover:-translate-y-1 hover:shadow-md`}><div className="mb-[18px] text-[11px] font-bold text-[#8B5CF6]">{s.num}</div><div className={`mb-[18px] flex h-11 w-11 items-center justify-center rounded-xl ${s.color==="video"?"bg-[#EEF6FF] text-[#3B82F6]":s.color==="chat"?"bg-[#EAF7FF] text-[#0EA5E9]":s.color==="whiteboard"?"bg-[#ECFDF5] text-[#10B981]":s.color==="mobility"?"bg-[#EEF2FF] text-[#6366F1]":s.color==="contact"?"bg-[#FFF7ED] text-[#F59E0B]":"bg-[#F4EEFF] text-[#8B5CF6]"}`}><i className={`fa-solid fa-${s.icon}`}></i></div><h3 className="mb-3 text-lg font-bold text-[#112868]">{s.title}</h3><p className="mb-5 text-[13px] leading-[1.8] text-[#667085]">{s.desc}</p><div className="flex flex-wrap gap-2">{s.tags.map((t,j)=><span key={j} className={`rounded-full px-2.5 py-1.5 text-[11px] font-semibold ${s.color==="video"?"bg-[#EEF6FF] text-[#3B82F6]":s.color==="chat"?"bg-[#EAF7FF] text-[#0EA5E9]":s.color==="whiteboard"?"bg-[#ECFDF5] text-[#10B981]":s.color==="mobility"?"bg-[#EEF2FF] text-[#6366F1]":s.color==="contact"?"bg-[#FFF7ED] text-[#F59E0B]":"bg-[#F4EEFF] text-[#8B5CF6]"}`}>{t}</span>)}</div></div>)}
                    </div>
                </div>
            </section>

            {/* MODERN PLATFORM SECTION */}
            <section className="bg-white px-[24px] py-20 font-sans md:px-[80px] md:py-[110px]">
                <div className="mx-auto grid max-w-[1300px] grid-cols-1 gap-[70px] lg:grid-cols-2">
                    <div><div className="mb-4 flex items-center gap-2.5 text-[11px] font-bold tracking-[2px] text-[#4F7BFF]"><span className="h-0.5 w-[18px] bg-[#4F7BFF]"></span>KEUNGGULAN PLATFORM</div><h2 className="mb-4 text-3xl font-extrabold leading-[1.1] text-[#112868] md:text-4xl lg:text-[52px]">Dirancang untuk Tim Modern</h2><p className="mb-[34px] max-w-[520px] text-[15px] leading-[1.9] text-[#667085]">Setiap fitur kami dibangun dengan mempertimbangkan pengalaman pengguna, keamanan enterprise, dan kemudahan administrasi IT.</p>
                        <div className="rounded-[22px] border border-[#E7E8FF] bg-[#F4F4FF] p-[18px]"><div className="mb-[18px] rounded-[14px] bg-white p-[18px_20px]"><h4 className="text-sm font-bold text-[#112868]">Meeting Analytics</h4><span className="text-[11px] text-[#94A3B8]">Minggu ini • 47 meeting</span></div>
                            {[{label:"Video",width:"72%"},{label:"Audio",width:"85%"},{label:"HD",width:"98%"},{label:"Quality",width:"98%"}].map((m,i)=><div key={i} className="mb-3.5 grid grid-cols-[50px_1fr_40px] items-center gap-3"><label className="text-[11px] text-[#64748B]">{m.label}</label><div className="h-1 rounded-full bg-[#E5E7EB] overflow-hidden"><span className={`block h-full rounded-full bg-[#7C4DFF]`} style={{width:m.width}}></span></div><strong className="text-[11px] text-[#64748B]">{m.width}</strong></div>)}
                            <div className="mt-5 flex items-center justify-between rounded-[14px] bg-white p-[18px_20px]"><span className="text-xs font-semibold text-[#112868]">Avg. Meeting Quality Score</span><h3 className="text-2xl font-extrabold text-[#6D28D9]">4.8 / 5</h3></div>
                        </div>
                    </div>
                    <div className="mt-0 lg:mt-[195px]"><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-[#F3E8FF] px-3.5 py-2 text-[11px] font-bold text-[#7C3AED]"><i className="fa-solid fa-video"></i>Video Conferencing</div><h2 className="mb-[18px] text-3xl font-extrabold leading-[1.2] text-[#112868] md:text-4xl lg:text-[42px]">Meeting Berkualitas Tinggi, Tanpa Gangguan</h2><p className="mb-6 leading-[1.9] text-[#667085]">Teknologi video conferencing kami menggunakan AI untuk noise cancellation, auto-framing kamera, dan adaptive bitrate — memastikan kualitas meeting tetap optimal bahkan di koneksi internet yang tidak stabil.</p>
                        <ul className="list-none">{[{text:"HD video hingga 4K, audio kristal jernih"},{text:"AI noise cancellation & background blur"},{text:"Recording cloud + live transcription otomatis"},{text:"Breakout rooms & polling interaktif"},{text:"Integrasi kalender Microsoft 365 & Google"}].map((item,i)=><li key={i} className="relative mb-3.5 pl-7 text-sm text-[#475569] before:absolute before:left-0 before:top-0 before:font-bold before:text-[#8B5CF6] before:content-['✓']">{item.text}</li>)}</ul>
                    </div>
                </div>

                {/* Team Messaging Row */}
                <div className="mt-[90px] grid grid-cols-1 gap-10 lg:grid-cols-2 lg:gap-20"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-[#EEF7FF] px-3.5 py-2 text-[11px] font-bold text-[#0EA5E9]"><i className="fa-solid fa-message"></i>Team Messaging</div><h2 className="mb-[18px] text-3xl font-extrabold leading-[1.2] text-[#112868] md:text-4xl lg:text-[42px]">Kolaborasi Tim yang Terorganisir & Cepat</h2><p className="mb-6 leading-[1.9] text-[#667085]">Hentikan rantai email yang panjang dan tidak terstruktur. Platform messaging kami mengorganisir percakapan per topik, project, dan tim — dengan history lengkap yang mudah dicari kapan pun.</p><ul className="list-none">{[{text:"Channel terorganisir per divisi & proyek"},{text:"Pencarian pesan & file di seluruh history"},{text:"Bot & workflow automation terintegrasi"},{text:"File sharing & preview langsung di chat"},{text:"Enkripsi end-to-end semua pesan & file"}].map((item,i)=><li key={i} className="relative mb-3.5 pl-7 text-sm text-[#475569] before:absolute before:left-0 before:top-0 before:font-bold before:text-[#0EA5E9] before:content-['✓']">{item.text}</li>)}</ul></div>
                    <div className="rounded-[22px] border border-[#DCE8FF] bg-[#EEF4FF] p-[18px]"><div className="rounded-2xl bg-white p-5"><div className="mb-6 text-[13px] font-bold text-[#112868]">#general-ops<span className="mt-1 block text-[11px] font-medium text-[#94A3B8]">43 anggota • aktif sekarang</span></div><div className="mb-[18px] max-w-[75%]"><strong className="mb-1 block text-xs text-[#112868]">Andi R.</strong><p className="text-xs leading-[1.6] text-[#475569]">Update deployment server sudah selesai jam 14.30 👍</p><small className="text-[10px] text-[#94A3B8]">14:32</small></div><div className="mb-[18px] ml-auto max-w-[75%] rounded-xl bg-[#0EA5E9] p-3"><p className="text-xs leading-[1.6] text-white">Noted! Report bisa langsung kirim ke channel #devops ya</p><small className="text-[10px] text-white/80">14:32</small></div><div className="mb-[18px] max-w-[75%]"><strong className="mb-1 block text-xs text-[#112868]">Budi P.</strong><p className="text-xs leading-[1.6] text-[#475569]">Oke siap, file sudah di-pin di channel</p><small className="text-[10px] text-[#94A3B8]">14:34</small></div><div className="mb-[18px] ml-auto max-w-[75%] rounded-xl bg-[#0EA5E9] p-3"><p className="text-xs leading-[1.6] text-white">Makasih semua, good job! 🚀</p><small className="text-[10px] text-white/80">14:35</small></div></div></div>
                </div>

                {/* Mobility Row */}
                <div className="mt-[90px] grid grid-cols-1 gap-10 lg:grid-cols-2 lg:gap-20"><div className="order-2 lg:order-1"><div className="rounded-[22px] border border-[#CDEFE0] bg-[#E8F8F1] p-[18px]"><div className="rounded-2xl bg-white p-[18px]"><div className="mb-[18px] flex items-center gap-3"><i className="fa-solid fa-laptop text-[#10B981]"></i><div><h4 className="text-sm text-[#112868]">Perangkat Terdaftar</h4><span className="text-[11px] text-[#94A3B8]">124 devices aktif</span></div></div><div className="mb-4 grid grid-cols-2 gap-3"><div className="flex items-center gap-2.5 rounded-[10px] border border-[#EEF2F7] p-3"><i className="fa-solid fa-desktop text-[#10B981]"></i><div><strong className="block text-xs text-[#112868]">Desktop</strong><span className="text-[11px] text-[#94A3B8]">68 unit online</span></div></div><div className="flex items-center gap-2.5 rounded-[10px] border border-[#EEF2F7] p-3"><i className="fa-solid fa-mobile-screen text-[#10B981]"></i><div><strong className="block text-xs text-[#112868]">Mobile</strong><span className="text-[11px] text-[#94A3B8]">42 unit online</span></div></div><div className="flex items-center gap-2.5 rounded-[10px] border border-[#EEF2F7] p-3"><i className="fa-solid fa-tablet-screen-button text-[#10B981]"></i><div><strong className="block text-xs text-[#112868]">Tablet</strong><span className="text-[11px] text-[#94A3B8]">14 unit online</span></div></div><div className="flex items-center gap-2.5 rounded-[10px] border border-[#EEF2F7] p-3"><i className="fa-solid fa-laptop text-[#10B981]"></i><div><strong className="block text-xs text-[#112868]">IP Phone</strong><span className="text-[11px] text-[#94A3B8]">Tersedia</span></div></div></div></div><div className="mt-3.5 rounded-2xl bg-white p-[18px]">{["Windows","iOS","Android"].map((os,i)=><div key={i} className="mb-3.5 grid grid-cols-[50px_1fr_40px] items-center gap-3"><label className="text-[11px] text-[#64748B]">{os}</label><div className="h-1 rounded-full bg-[#E5E7EB] overflow-hidden"><span className="block h-full rounded-full bg-[#10B981]" style={{width:os==="Windows"?"56%":os==="iOS"?"28%":"16%"}}></span></div><strong className="text-[11px] text-[#64748B]">{os==="Windows"?"56%":os==="iOS"?"28%":"16%"}</strong></div>)}</div></div></div>
                    <div className="order-1 lg:order-2"><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-[#ECFDF5] px-3.5 py-2 text-[11px] font-bold text-[#10B981]"><i className="fa-solid fa-mobile-screen"></i>Mobilitas & MDM</div><h2 className="mb-[18px] text-3xl font-extrabold leading-[1.2] text-[#112868] md:text-4xl lg:text-[42px]">Bekerja dari Mana Saja, Perangkat Apa Pun</h2><p className="mb-6 leading-[1.9] text-[#667085]">Solusi UCC kami berjalan secara native di semua platform — Windows, macOS, iOS, Android — dengan pengalaman yang konsisten dan manajemen perangkat terpusat melalui MDM terintegrasi.</p><ul className="list-none">{[{text:"Native app di semua OS & platform"},{text:"SSO & MFA untuk keamanan akses terpusat"},{text:"Offline mode — tetap produktif tanpa internet"},{text:"Push notification cerdas, tidak mengganggu"},{text:"Manajemen device & kebijakan dari satu konsol"}].map((item,i)=><li key={i} className="relative mb-3.5 pl-7 text-sm text-[#475569] before:absolute before:left-0 before:top-0 before:font-bold before:text-[#10B981] before:content-['✓']">{item.text}</li>)}</ul></div>
                </div>
            </section>

            {/* IMPLEMENTATION PROCESS SECTION */}
            <section className="bg-[#102B73] px-[24px] py-20 font-sans md:px-[80px] md:py-[110px]">
                <div className="mx-auto mb-[70px] max-w-[760px] text-center"><div className="mb-[18px] flex items-center justify-center gap-2.5 text-[11px] font-bold tracking-[2px] text-[#A5B4FC]"><span className="h-0.5 w-5 bg-[#A5B4FC]"></span>CARA KERJA KAMI</div><h2 className="mb-[18px] text-3xl font-extrabold leading-[1.15] text-white md:text-4xl lg:text-[48px]">Implementasi Terstruktur, Migrasi Tanpa Hambatan</h2><p className="text-[15px] leading-[1.9] text-white/65">Tim certified engineer UTI mengelola seluruh proses — dari asesmen kebutuhan hingga go-live — dengan downtime minimal dan adopsi user yang tinggi.</p></div>
                <div className="mx-auto grid max-w-[1300px] grid-cols-1 gap-[18px] md:grid-cols-2 lg:grid-cols-4">
                    {[{icon:"magnifying-glass",num:"01",title:"Discovery & Assessment",desc:"Analisis infrastruktur komunikasi eksisting, pola penggunaan, kebutuhan integrasi, dan jumlah user untuk merancang solusi yang paling sesuai."},{icon:"window-maximize",num:"02",title:"Design & Pilot Platform",desc:"Tim arsitek UTI merancang arsitektur UCC yang optimal — menentukan platform, lisensi, hardware, dan roadmap integrasi berdasarkan kebutuhan dan anggaran Anda."},{icon:"pen-ruler",num:"03",title:"Implementation & Migration",desc:"Deployment bertahap dengan pilot group terlebih dahulu — migrasi data, konfigurasi integrasi, dan testing menyeluruh sebelum rollout ke seluruh organisasi."},{icon:"users",num:"04",title:"Training & Go-live Support",desc:"Pelatihan end-user dan admin yang komprehensif, disertai hypercare support 30 hari pasca go-live untuk memastikan adopsi maksimal di seluruh tim."}].map((proc,i)=><div key={i} className="relative min-h-[210px] rounded-[14px] border border-white/10 bg-white/10 p-6"><div className="mb-[18px] flex h-[38px] w-[38px] items-center justify-center rounded-[10px] bg-[#8B5CF6]/20 text-[#A78BFA]"><i className={`fa-solid fa-${proc.icon}`}></i></div><div className="absolute right-[18px] top-[18px] text-[52px] font-extrabold leading-none text-white/5">{proc.num}</div><h3 className="mb-3 text-[15px] font-bold text-white">{proc.title}</h3><p className="text-[13px] leading-[1.8] text-white/65">{proc.desc}</p></div>)}
                </div>
            </section>
        </main>
        <CTAForm backgroundColor="#102B73" brandColor="#102B73" />
        </>
    );
}